image: nrdtech/python-build-image:1.0

# NOTE:
# - Be sure to configure the environment variagbles:
#   - env.global
#   - env.staging
#   - env.prod
#   - env.terraform

pipelines:
  branches:
    staging:
      - step:
          name: Deploy
          services:
            - docker
          oidc: true
          script:
            - ENVIRONMENT=staging bash ./deploy.sh
    production:
      - step:
          name: Deploy
          services:
            - docker
          oidc: true
          script:
            - ENVIRONMENT=prod bash ./deploy.sh
  custom:
    un-deploy-staging:
      - step:
          name: Deploy
          services:
            - docker
          oidc: true
          script:
            - ENVIRONMENT=staging bash ./deploy.sh -d
    un-deploy-production:
      - step:
          name: Deploy
          services:
            - docker
          oidc: true
          script:
            - ENVIRONMENT=prod bash ./deploy.sh -d
